project:
  type: website
  output-dir: docs

website:
  title: "Hunter Ross"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project.qmd
      - Plant_Identification.qmd
      - resume.qmd

format:
  html:
    theme: Yeti
    css: styles.css
    toc: true

editor: visual

