---
title: "Flora and Fauna Observations"
---


```{r}
#| echo: false
#| warning: false
#| message: false

#load in packages
library(tidyverse)
library(leaflet)
library(leaflet.extras)

#read in data
obs <- read.csv("iNat_observations/observations.csv")
```


```{r}
#| echo: false
#| warning: false
#| message: false

#some cleaning 
#first get just location by selecting just he long and lat
location <- obs |> 
  select(longitude, latitude, scientific_name) 


```



```{r}
#| echo: false
#| warning: false
#| message: false

#create a map
Observation_map <-  leaflet() |> 
  #add google map
  addTiles(urlTemplate = "https://mts1.google.com/vt/lyrs=s&hl=en&src=app&x={x}&y={y}&z={z}&s=G", attribution = 'Google') |> 
  addTiles() |> 
  addCircleMarkers(data= location, label = location$scientific_name) |> 

  #add mini map
  addMiniMap(toggleDisplay = TRUE, minimized = TRUE) |> 

  #set vew to open over Santa barbara
  setView(lng = -119.83, lat = 34.44, zoom = 9) 

  

Observation_map
```









